function [trace]=createTrace(traceImport)

trace.radii = traceImport.value(traceImport.name == 'radii',:);

trace.K = [ traceImport.value(traceImport.name == 'La_K',:) ;...
            traceImport.value(traceImport.name == 'Ce_K',:) ;...
            traceImport.value(traceImport.name == 'Pr_K',:) ;...
            traceImport.value(traceImport.name == 'Nd_K',:) ;...
            traceImport.value(traceImport.name == 'Sm_K',:) ;...
            traceImport.value(traceImport.name == 'Eu_K',:) ;...
            traceImport.value(traceImport.name == 'Gd_K',:) ;...
            traceImport.value(traceImport.name == 'Tb_K',:) ;...
            traceImport.value(traceImport.name == 'Dy_K',:) ;...
            traceImport.value(traceImport.name == 'Ho_K',:) ;...
            traceImport.value(traceImport.name == 'Er_K',:) ;...
            traceImport.value(traceImport.name == 'Yb_K',:) ;...
            traceImport.value(traceImport.name == 'Lu_K',:)];

trace.D = [ traceImport.value(traceImport.name == 'La_D',:) ;...
            traceImport.value(traceImport.name == 'Ce_D',:) ;...
            traceImport.value(traceImport.name == 'Pr_D',:) ;...
            traceImport.value(traceImport.name == 'Nd_D',:) ;...
            traceImport.value(traceImport.name == 'Sm_D',:) ;...
            traceImport.value(traceImport.name == 'Eu_D',:) ;...
            traceImport.value(traceImport.name == 'Gd_D',:) ;...
            traceImport.value(traceImport.name == 'Tb_D',:) ;...
            traceImport.value(traceImport.name == 'Dy_D',:) ;...
            traceImport.value(traceImport.name == 'Ho_D',:) ;...
            traceImport.value(traceImport.name == 'Er_D',:) ;...
            traceImport.value(traceImport.name == 'Yb_D',:) ;...
            traceImport.value(traceImport.name == 'Lu_D',:)];

trace.E = [ traceImport.value(traceImport.name == 'La_E',:) ;...
            traceImport.value(traceImport.name == 'Ce_E',:) ;...
            traceImport.value(traceImport.name == 'Pr_E',:) ;...
            traceImport.value(traceImport.name == 'Nd_E',:) ;...
            traceImport.value(traceImport.name == 'Sm_E',:) ;...
            traceImport.value(traceImport.name == 'Eu_E',:) ;...
            traceImport.value(traceImport.name == 'Gd_E',:) ;...
            traceImport.value(traceImport.name == 'Tb_E',:) ;...
            traceImport.value(traceImport.name == 'Dy_E',:) ;...
            traceImport.value(traceImport.name == 'Ho_E',:) ;...
            traceImport.value(traceImport.name == 'Er_E',:) ;...
            traceImport.value(traceImport.name == 'Yb_E',:) ;...
            traceImport.value(traceImport.name == 'Lu_E',:)];

trace.V = [ traceImport.value(traceImport.name == 'La_V',:) ;...
            traceImport.value(traceImport.name == 'Ce_V',:) ;...
            traceImport.value(traceImport.name == 'Pr_V',:) ;...
            traceImport.value(traceImport.name == 'Nd_V',:) ;...
            traceImport.value(traceImport.name == 'Sm_V',:) ;...
            traceImport.value(traceImport.name == 'Eu_V',:) ;...
            traceImport.value(traceImport.name == 'Gd_V',:) ;...
            traceImport.value(traceImport.name == 'Tb_V',:) ;...
            traceImport.value(traceImport.name == 'Dy_V',:) ;...
            traceImport.value(traceImport.name == 'Ho_V',:) ;...
            traceImport.value(traceImport.name == 'Er_V',:) ;...
            traceImport.value(traceImport.name == 'Yb_V',:) ;...
            traceImport.value(traceImport.name == 'Lu_V',:)];   
